services:
    database:
        image: postgres:17
        restart: always
        ports:
            - '5432:5432'
        env_file:
            - database.env
        volumes:
            - ./docker/postgres-data:/var/lib/postgresql/data
    backend:
        build:
            context: .
            dockerfile: Dockerfile
            target: production
        ports:
            - '8080:8080'
        env_file:
            - .env.dc
        depends_on:
            - 'database'
        tty: true
        restart: unless-stopped
