services:
    database:
        image: postgres:17
        restart: always
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: message_database
        volumes:
            - ./docker/postgres-data:/var/lib/postgresql/data
    backend:
        build:
            context: .
            dockerfile: Dockerfile
            target: development
        ports:
            - '8080:8080'
        env_file:
            - .env.dc
        depends_on:
            - 'database'
        tty: true
        restart: unless-stopped
        volumes:
            - ./:/home/node/app
            - /home/node/app/node_modules
